// Ocular surface, anterior segment, lens and pressure.
//
// Clinical wording is textbook-level and awaiting review — see docs/atlas-review.md.

import type { ConditionEntry } from "./types";

const lerp = (a: number, b: number, t: number) => a + (b - a) * Math.min(1, Math.max(0, t));

export const SURFACE: ConditionEntry[] = [
  {
    id: "dry_eye",
    name: "Dry eye disease",
    region: "surface",
    view: "exterior",
    description:
      "The tear film breaks up too quickly or is of poor quality, leaving the surface of the eye exposed.",
    experience:
      "Grittiness, burning, watering, and vision that blurs between blinks and clears when you blink.",
    clinical: "Reduced tear break-up time, surface staining, meibomian gland dysfunction.",
    profiles: ["dry_eye"],
    vocabulary: ["tear film", "TBUT", "meibomian", "artificial tears", "punctal plug"],
    at: (s) => ({ delta: { scleraVessels: lerp(0.5, 0.9, s), corneaClarity: 1 - 0.15 * s } }),
    simulation: { kind: "blur" },
    gradable: true,
  },
  {
    id: "corneal_abrasion",
    name: "Corneal abrasion",
    region: "surface",
    view: "exterior",
    description: "A scratch through the surface layer of the cornea.",
    experience: "Sharp pain, watering, light sensitivity and a feeling that something is in the eye.",
    clinical: "An epithelial defect that stains with fluorescein.",
    vocabulary: ["abrasion", "fluorescein", "epithelial defect"],
    at: (s) => ({ delta: { scleraVessels: lerp(0.6, 1, s), corneaClarity: 1 - 0.2 * s } }),
    simulation: { kind: "photophobia" },
    gradable: true,
  },
  {
    id: "corneal_ulcer",
    name: "Corneal ulcer",
    region: "surface",
    view: "exterior",
    description: "An infected or inflamed defect that extends into the deeper corneal tissue.",
    experience: "Pain, redness, marked light sensitivity and blurred vision.",
    clinical: "A stromal infiltrate with an overlying epithelial defect.",
    vocabulary: ["ulcer", "infiltrate", "keratitis", "corneal scrape"],
    at: (s) => ({ delta: { scleraVessels: 1, corneaClarity: 1 - 0.45 * s } }),
    simulation: { kind: "blur" },
    gradable: true,
  },
  {
    id: "keratoconus",
    name: "Keratoconus",
    region: "surface",
    view: "cross_section",
    description: "The cornea thins and bulges forward into a cone shape.",
    experience:
      "Vision that distorts and ghosts, glare and starbursts at night, and a spectacle prescription that keeps changing.",
    clinical: "Corneal steepening and thinning on topography and pachymetry.",
    profiles: ["cornea"],
    vocabulary: ["keratoconus", "topography", "cross-linking", "scleral lens"],
    at: (s) => ({ delta: { corneaClarity: 1 - 0.1 * s } }),
    simulation: { kind: "glare" },
    gradable: true,
  },
  {
    id: "corneal_oedema",
    name: "Corneal oedema",
    region: "surface",
    view: "cross_section",
    description: "Fluid builds up in the cornea when its inner pumping layer is not keeping up.",
    experience: "Misty vision, worst on waking and clearing through the day, with halos around lights.",
    clinical: "Corneal thickening with stromal haze or microcystic epithelial change.",
    profiles: ["cornea"],
    vocabulary: ["oedema", "endothelium", "pachymetry", "bullous keratopathy"],
    at: (s) => ({ delta: { corneaClarity: 1 - 0.4 * s } }),
    simulation: { kind: "halos" },
    gradable: true,
  },
  {
    id: "fuchs_dystrophy",
    name: "Fuchs' endothelial dystrophy",
    region: "surface",
    view: "cross_section",
    description: "The cells that keep the cornea clear gradually reduce in number.",
    experience: "Vision that is misty in the morning and improves during the day, over years.",
    clinical: "Guttae on specular examination, with corneal thickening over time.",
    profiles: ["cornea"],
    vocabulary: ["guttata", "endothelial count", "DMEK", "DSAEK"],
    at: (s) => ({ delta: { corneaClarity: 1 - 0.3 * s } }),
    simulation: { kind: "contrast_loss" },
    gradable: true,
  },
  {
    id: "pterygium",
    name: "Pterygium",
    region: "surface",
    view: "exterior",
    description: "A wedge of conjunctival tissue grows onto the cornea, usually from the nasal side.",
    experience: "Often cosmetic and irritating; vision changes only if it reaches the visual axis.",
    clinical: "A fibrovascular growth crossing the limbus.",
    vocabulary: ["pterygium", "pinguecula", "limbus"],
    at: (s) => ({ delta: { scleraVessels: lerp(0.5, 0.9, s) } }),
    gradable: false,
  },
  {
    id: "conjunctivitis",
    name: "Conjunctivitis",
    region: "surface",
    view: "exterior",
    description: "Inflammation of the membrane covering the white of the eye and inner eyelids.",
    experience: "Redness, discharge, grittiness; vision itself is usually unaffected.",
    clinical: "Conjunctival injection with discharge; the cornea is clear.",
    vocabulary: ["conjunctivitis", "injection", "discharge"],
    at: (s) => ({ delta: { scleraVessels: lerp(0.7, 1, s) } }),
    gradable: true,
  },
  {
    id: "subconjunctival_haemorrhage",
    name: "Subconjunctival haemorrhage",
    region: "surface",
    view: "exterior",
    description: "A small vessel under the conjunctiva bleeds, producing a flat red patch.",
    experience: "It looks alarming and feels like nothing. Vision is not affected.",
    clinical: "A well-defined flat area of blood with a clear cornea and normal pupil.",
    vocabulary: ["subconjunctival haemorrhage"],
    at: (s) => ({ delta: { scleraVessels: lerp(0.8, 1, s) } }),
    gradable: false,
  },
  {
    id: "episcleritis",
    name: "Episcleritis and scleritis",
    region: "surface",
    view: "exterior",
    description: "Inflammation of the layers beneath the conjunctiva, mild in one form and deep in the other.",
    experience:
      "Episcleritis is uncomfortable and localised; scleritis is a deep, boring ache that can wake you at night.",
    clinical: "Sectoral injection; deep vascular plexus involvement distinguishes scleritis.",
    vocabulary: ["episcleritis", "scleritis", "phenylephrine test"],
    at: (s) => ({ delta: { scleraVessels: lerp(0.7, 1, s) } }),
    gradable: true,
  },
  {
    id: "blepharitis",
    name: "Blepharitis",
    region: "surface",
    view: "exterior",
    description: "Inflammation of the eyelid margins and the glands within them.",
    experience: "Crusting, sore lid margins, and dryness that comes and goes.",
    clinical: "Lid margin debris, telangiectasia and meibomian gland dysfunction.",
    profiles: ["dry_eye"],
    vocabulary: ["blepharitis", "meibomian", "lid hygiene"],
    at: (s) => ({ delta: { scleraVessels: lerp(0.5, 0.8, s) } }),
    gradable: true,
  },
];

export const ANTERIOR: ConditionEntry[] = [
  {
    id: "anterior_uveitis",
    name: "Anterior uveitis",
    region: "anterior",
    view: "cross_section",
    description: "Inflammation inside the front chamber of the eye.",
    experience: "Aching, redness around the coloured part, light sensitivity and blurring.",
    clinical: "Cells and flare in the anterior chamber, keratic precipitates, sometimes synechiae.",
    profiles: ["uveitis"],
    vocabulary: ["iritis", "cells and flare", "keratic precipitates", "synechiae", "cycloplegic"],
    at: (s) => ({
      delta: { scleraVessels: lerp(0.7, 1, s), corneaClarity: 1 - 0.2 * s, pupilMm: 3 - s },
    }),
    simulation: { kind: "photophobia" },
    gradable: true,
  },
  {
    id: "hyphaema",
    name: "Hyphaema",
    region: "anterior",
    view: "cross_section",
    description: "Blood collects in the front chamber of the eye, usually after an injury.",
    experience: "Blurring, and a visible level of blood in the eye.",
    clinical: "A layered red level in the anterior chamber; pressure needs watching.",
    vocabulary: ["hyphaema", "layered blood"],
    at: (s) => ({ delta: { corneaClarity: 1 - 0.25 * s, scleraVessels: 0.9 } }),
    simulation: { kind: "blur" },
    gradable: true,
  },
  {
    id: "cataract",
    name: "Cataract",
    region: "anterior",
    view: "cross_section",
    description: "The eye's natural lens becomes cloudy, scattering light on its way through.",
    experience:
      "Glare and starbursts at night, colours looking duller, and vision that dims gradually over years.",
    clinical: "Lens opacity graded by type — nuclear, cortical or posterior subcapsular.",
    profiles: ["cataract"],
    vocabulary: ["nuclear sclerosis", "PSC", "phaco", "IOL"],
    at: (s) => ({ delta: { lensOpacity: lerp(0.15, 0.9, s) } }),
    simulation: { kind: "glare" },
    gradable: true,
  },
  {
    id: "pco",
    name: "Posterior capsule opacification",
    region: "anterior",
    view: "cross_section",
    description:
      "The membrane behind a lens implant becomes cloudy months or years after cataract surgery.",
    experience: "Vision gradually dimming again, with glare — often described as the cataract coming back.",
    clinical: "Opacification of the posterior capsule behind the intraocular lens.",
    profiles: ["cataract"],
    vocabulary: ["PCO", "YAG capsulotomy"],
    at: (s) => ({ delta: { lensOpacity: lerp(0.1, 0.55, s) } }),
    simulation: { kind: "contrast_loss" },
    gradable: true,
  },
  {
    id: "pseudophakia",
    name: "After cataract surgery",
    region: "anterior",
    view: "cross_section",
    description: "The natural lens has been replaced with a clear artificial implant.",
    experience:
      "Brighter, often bluer-looking vision. Some people notice reflections or a temporary crescent of light at the edge.",
    clinical: "A well-centred intraocular lens in the capsular bag.",
    profiles: ["cataract"],
    vocabulary: ["IOL", "pseudophakia", "dysphotopsia"],
    at: () => ({ delta: { lensOpacity: 0 } }),
    gradable: false,
  },
  {
    id: "open_angle_glaucoma",
    name: "Primary open-angle glaucoma",
    region: "anterior",
    view: "fundus",
    description:
      "Damage to the optic nerve, usually in the context of eye pressure that is too high for that nerve.",
    experience:
      "Nothing for a long time. Field loss starts away from the centre and is not noticed until it is substantial, which is why monitoring matters.",
    clinical: "Increasing cup-to-disc ratio, rim thinning, and matching field defects.",
    imaging: "OCT of the nerve fibre layer, and visual fields.",
    profiles: ["glaucoma"],
    vocabulary: ["IOP", "cup-to-disc", "RNFL", "visual field", "latanoprost", "trabeculectomy"],
    at: (s) => ({ delta: { cupDisc: lerp(0.35, 0.9, s) } }),
    annotations: [{ x: 0.68, y: 0.485, text: "The cup, widening as rim tissue is lost" }],
    simulation: { kind: "arcuate_loss" },
    gradable: true,
  },
  {
    id: "angle_closure",
    name: "Acute angle closure",
    region: "anterior",
    view: "cross_section",
    description: "The drainage angle closes suddenly and the pressure inside the eye rises quickly.",
    experience:
      "A painful, red eye with blurred vision, haloes around lights, headache and often nausea. This is one of the situations that needs assessment straight away.",
    clinical: "A shallow chamber, hazy cornea, and a fixed mid-dilated pupil with high pressure.",
    profiles: ["glaucoma"],
    vocabulary: ["angle closure", "gonioscopy", "iridotomy"],
    at: (s) => ({
      delta: { corneaClarity: 1 - 0.45 * s, pupilMm: 5.5, scleraVessels: lerp(0.8, 1, s) },
    }),
    simulation: { kind: "halos" },
    gradable: true,
  },
  {
    id: "ocular_hypertension",
    name: "Ocular hypertension",
    region: "anterior",
    view: "fundus",
    description: "Eye pressure above the usual range, without damage to the optic nerve.",
    experience: "Nothing. It is found on examination and monitored.",
    clinical: "Raised IOP with a healthy disc and normal fields.",
    profiles: ["glaucoma"],
    vocabulary: ["ocular hypertension", "IOP", "CCT"],
    at: () => ({ delta: { cupDisc: 0.32 } }),
    gradable: false,
  },
];
