// Vitreous and retina.
//
// Clinical wording here is textbook-level and awaiting review — see docs/atlas-review.md.
// Nothing describes any individual, and nothing tells anyone what to do.

import type { ConditionEntry } from "./types";

const lerp = (a: number, b: number, t: number) => a + (b - a) * Math.min(1, Math.max(0, t));

export const VITREORETINA: ConditionEntry[] = [
  {
    id: "vitreous_floaters",
    name: "Vitreous floaters",
    region: "vitreoretina",
    view: "fundus",
    description:
      "Condensations in the vitreous gel that cast shadows on the retina as light passes through.",
    experience:
      "Drifting dots, threads or cobwebs that move when the eye moves and settle a moment later. Usually clearer against a bright, plain background.",
    clinical: "Vitreous opacities, seen on examination of the vitreous cavity.",
    profiles: ["pvd_floaters", "retinal_detachment"],
    vocabulary: ["vitreous opacity", "muscae volitantes", "Weiss ring"],
    at: (s) => ({ lesions: { haze: 0.08 * s } }),
    simulation: { kind: "floaters" },
    gradable: true,
  },
  {
    id: "pvd",
    name: "Posterior vitreous detachment",
    region: "vitreoretina",
    view: "cross_section",
    description:
      "The vitreous gel separates from the surface of the retina. It is common with age and is often the reason new floaters appear.",
    experience:
      "New floaters, sometimes a ring-shaped one, and sometimes brief arcs of light in the periphery as the gel tugs on the retina.",
    clinical: "A Weiss ring and a detached posterior hyaloid face on examination.",
    profiles: ["pvd_floaters"],
    vocabulary: ["PVD", "Weiss ring", "posterior hyaloid"],
    at: (s) => ({ lesions: { haze: 0.05 * s } }),
    simulation: { kind: "floaters" },
    gradable: true,
  },
  {
    id: "retinal_tear",
    name: "Retinal tear",
    region: "vitreoretina",
    view: "fundus",
    description:
      "A break in the retina, often where the vitreous has pulled on it. Fluid can pass through a break and lift the retina away.",
    experience:
      "Often a sudden increase in floaters, or flashes of light, though a tear can also be found without any symptoms at all.",
    clinical: "A horseshoe or operculated break, usually in the peripheral retina.",
    imaging: "Seen on dilated examination; wide-field imaging can document it.",
    profiles: ["retinal_detachment"],
    vocabulary: ["horseshoe tear", "operculated hole", "retinopexy"],
    at: (s) => ({ lesions: { tear: lerp(0.4, 1, s) } }),
    annotations: [{ x: 0.28, y: 0.24, text: "The break, with the flap pulled forward" }],
    simulation: { kind: "floaters" },
    gradable: true,
  },
  {
    id: "retinal_hole",
    name: "Retinal hole",
    region: "vitreoretina",
    view: "fundus",
    description: "A round break in the retina without traction pulling on its edge.",
    experience: "Often nothing at all; holes are frequently found during a routine examination.",
    clinical: "A round, full-thickness break, sometimes within an area of lattice.",
    profiles: ["retinal_detachment"],
    vocabulary: ["atrophic hole", "round hole"],
    at: (s) => ({ lesions: { tear: 0.35 * s } }),
    gradable: false,
  },
  {
    id: "lattice",
    name: "Lattice degeneration",
    region: "vitreoretina",
    view: "fundus",
    description: "Areas where the retina is thinner than usual, most often in the periphery.",
    experience: "Nothing. Lattice is found on examination and is monitored rather than felt.",
    clinical: "Circumferential areas of thinning with overlying vitreous liquefaction.",
    profiles: ["retinal_detachment"],
    vocabulary: ["lattice", "peripheral thinning"],
    at: (s) => ({ lesions: { boneSpicules: 0.06 * s } }),
    gradable: false,
  },
  {
    id: "rhegmatogenous_detachment",
    name: "Rhegmatogenous retinal detachment",
    region: "vitreoretina",
    view: "fundus",
    description:
      "Fluid passes through a break and separates the retina from the wall of the eye. The separated area cannot send a usable image.",
    experience:
      "A shadow or curtain that comes across part of the vision, often after a period of new floaters or flashes. The shadow appears on the opposite side from the affected retina.",
    clinical:
      "An elevated, mobile retina with a causative break; whether the macula is still attached is a key distinction.",
    imaging: "Documented on examination and wide-field imaging; ultrasound if the view is obscured.",
    profiles: ["retinal_detachment"],
    vocabulary: ["rhegmatogenous", "macula-on", "macula-off", "bullous", "subretinal fluid"],
    at: (s) => ({
      lesions: { detachment: lerp(0.25, 1, s), maculaOff: s > 0.72, tear: 0.5 },
    }),
    annotations: [
      { x: 0.3, y: 0.3, text: "Detached, folded retina" },
      { x: 0.5, y: 0.5, text: "Macula — still attached until the detachment reaches it" },
    ],
    simulation: { kind: "curtain", retinalQuadrant: "superior" },
    gradable: true,
  },
  {
    id: "tractional_detachment",
    name: "Tractional retinal detachment",
    region: "vitreoretina",
    view: "fundus",
    description:
      "Scar tissue on the retinal surface contracts and pulls the retina away, without a break.",
    experience: "Vision changes gradually rather than suddenly, and may distort before it dims.",
    clinical: "A taut, immobile retina with fibrovascular proliferation, most often in diabetes.",
    profiles: ["diabetic_eye"],
    vocabulary: ["tractional", "fibrovascular proliferation"],
    at: (s) => ({ lesions: { detachment: 0.5 * s, neovascular: 0.5 * s, membrane: 0.4 * s } }),
    simulation: { kind: "curtain", retinalQuadrant: "inferior" },
    gradable: true,
  },
  {
    id: "erm",
    name: "Epiretinal membrane",
    region: "vitreoretina",
    view: "fundus",
    description: "A thin sheet of tissue forms on the retinal surface and can contract.",
    experience:
      "Straight lines looking bent or wavy, and objects sometimes appearing a different size in one eye.",
    clinical: "A glinting membrane with retinal striae; contraction distorts the macula.",
    imaging: "OCT shows the membrane and the wrinkling beneath it.",
    profiles: ["macular_surface"],
    vocabulary: ["ERM", "macular pucker", "membrane peel", "metamorphopsia"],
    at: (s) => ({ lesions: { membrane: lerp(0.3, 1, s) } }),
    simulation: { kind: "metamorphopsia" },
    gradable: true,
  },
  {
    id: "macular_hole",
    name: "Macular hole",
    region: "vitreoretina",
    view: "fundus",
    description: "A full-thickness opening at the very centre of the macula.",
    experience: "A missing or distorted patch right in the middle of vision, in that eye alone.",
    clinical: "A round full-thickness defect at the fovea, staged by size and by traction.",
    imaging: "OCT shows the stage and the size.",
    profiles: ["macular_surface"],
    vocabulary: ["macular hole", "stage", "ILM peel", "face-down posturing"],
    at: (s) => ({ lesions: { macularHole: lerp(0.3, 1, s) } }),
    simulation: { kind: "central_scotoma" },
    gradable: true,
  },
  {
    id: "vmt",
    name: "Vitreomacular traction",
    region: "vitreoretina",
    view: "cross_section",
    description: "The vitreous stays attached at the macula and pulls on it as it separates elsewhere.",
    experience: "Distortion, and sometimes a change in the size things appear.",
    clinical: "Persistent attachment at the fovea with distortion of the foveal contour.",
    imaging: "OCT.",
    profiles: ["macular_surface"],
    vocabulary: ["VMT", "vitreomacular adhesion"],
    at: (s) => ({ lesions: { membrane: 0.4 * s } }),
    simulation: { kind: "metamorphopsia" },
    gradable: true,
  },
  {
    id: "csr",
    name: "Central serous chorioretinopathy",
    region: "vitreoretina",
    view: "fundus",
    description: "Fluid collects under the central retina, lifting a small blister of it.",
    experience:
      "A dim or smudged patch in the centre, things looking smaller or further away, and colours looking washed out.",
    clinical: "A serous detachment of the neurosensory retina at the macula.",
    imaging: "OCT shows the subretinal fluid.",
    vocabulary: ["CSR", "CSCR", "serous detachment"],
    at: (s) => ({ lesions: { subretinalBleed: 0.15 * s, membrane: 0.15 * s } }),
    simulation: { kind: "central_scotoma" },
    gradable: true,
  },
  {
    id: "dry_amd",
    name: "Dry age-related macular degeneration",
    region: "vitreoretina",
    view: "fundus",
    description:
      "Deposits called drusen build up at the macula, and over time areas of the pigment layer can be lost.",
    experience:
      "Central vision becoming less sharp, needing more light to read, and — where atrophy develops — a missing patch in the middle.",
    clinical: "Drusen, pigmentary change, and geographic atrophy in advanced disease.",
    imaging: "OCT and autofluorescence map the atrophy.",
    profiles: ["amd"],
    vocabulary: ["drusen", "geographic atrophy", "AREDS"],
    at: (s) => ({
      lesions: { drusen: lerp(0.25, 1, s), atrophy: s > 0.6 ? (s - 0.6) / 0.4 : 0 },
      delta: { macularPigment: 0.4 },
    }),
    simulation: { kind: "central_scotoma" },
    gradable: true,
  },
  {
    id: "wet_amd",
    name: "Neovascular (wet) age-related macular degeneration",
    region: "vitreoretina",
    view: "fundus",
    description:
      "New, fragile vessels grow beneath the macula and leak fluid or blood, which distorts and obscures central vision.",
    experience:
      "Straight lines bending, a dark or empty patch appearing in the centre, and change that can happen over days rather than years.",
    clinical: "Choroidal neovascularisation with subretinal fluid, haemorrhage or exudate.",
    imaging: "OCT, and angiography where the membrane needs to be located.",
    profiles: ["amd"],
    vocabulary: ["CNV", "anti-VEGF", "aflibercept", "ranibizumab", "subretinal fluid"],
    at: (s) => ({
      lesions: { drusen: 0.4, subretinalBleed: lerp(0.3, 1, s), exudates: 0.5 * s },
    }),
    simulation: { kind: "metamorphopsia" },
    gradable: true,
  },
  {
    id: "npdr",
    name: "Non-proliferative diabetic retinopathy",
    region: "vitreoretina",
    view: "fundus",
    description:
      "Damage to the small retinal vessels causes them to leak and to close off, producing haemorrhages and deposits.",
    experience:
      "Often nothing at all in the early stages, which is why screening exists. Blurring appears if the macula is affected.",
    clinical:
      "Microaneurysms, dot-and-blot haemorrhages, hard exudates, cotton-wool spots and venous changes, graded mild to severe.",
    imaging: "Retinal photography for screening; OCT for the macula.",
    profiles: ["diabetic_eye"],
    vocabulary: ["retinopathy", "microaneurysm", "R1", "R2", "screening"],
    at: (s) => ({
      lesions: {
        dotBlot: lerp(0.15, 0.9, s),
        exudates: lerp(0, 0.6, s),
        cottonWool: s > 0.5 ? (s - 0.5) * 1.4 : 0,
        venousEngorgement: 0.4 * s,
      },
    }),
    simulation: { kind: "blur" },
    gradable: true,
  },
  {
    id: "pdr",
    name: "Proliferative diabetic retinopathy",
    region: "vitreoretina",
    view: "fundus",
    description:
      "New vessels grow in response to areas of retina that have lost their blood supply. They are fragile and can bleed.",
    experience:
      "A sudden shower of floaters or a red haze if a vessel bleeds; otherwise it can be silent until it is advanced.",
    clinical: "Neovascularisation at the disc or elsewhere, with or without vitreous haemorrhage.",
    imaging: "Wide-field imaging and angiography show the non-perfused retina.",
    profiles: ["diabetic_eye"],
    vocabulary: ["PDR", "NVD", "NVE", "PRP", "vitreous haemorrhage"],
    at: (s) => ({
      lesions: {
        dotBlot: 0.6,
        neovascular: lerp(0.3, 1, s),
        haze: 0.25 * s,
        cottonWool: 0.4,
      },
    }),
    simulation: { kind: "floaters" },
    gradable: true,
  },
  {
    id: "dmo",
    name: "Diabetic macular oedema",
    region: "vitreoretina",
    view: "fundus",
    description: "Fluid collects within the layers of the central retina.",
    experience: "Central blurring and distortion, which can fluctuate.",
    clinical: "Retinal thickening at the macula, with or without exudate.",
    imaging: "OCT central subfield thickness is the number that is tracked.",
    profiles: ["diabetic_eye"],
    vocabulary: ["DMO", "DME", "central subfield thickness", "anti-VEGF"],
    at: (s) => ({ lesions: { exudates: lerp(0.3, 1, s), dotBlot: 0.4, membrane: 0.2 * s } }),
    simulation: { kind: "metamorphopsia" },
    gradable: true,
  },
  {
    id: "prp_treated",
    name: "After panretinal laser",
    region: "vitreoretina",
    view: "fundus",
    description:
      "Laser is applied across the peripheral retina to reduce the drive for new vessels to grow.",
    experience:
      "Peripheral and night vision are often reduced afterwards; this is the trade the treatment makes.",
    clinical: "Scattered chorioretinal scars sparing the macula.",
    profiles: ["diabetic_eye"],
    vocabulary: ["PRP", "panretinal photocoagulation", "laser burns"],
    at: (s) => ({ lesions: { prp: lerp(0.4, 1, s), dotBlot: 0.3 } }),
    simulation: { kind: "peripheral_loss" },
    gradable: true,
  },
  {
    id: "brvo",
    name: "Branch retinal vein occlusion",
    region: "vitreoretina",
    view: "fundus",
    description: "One branch of the retinal vein is blocked, and the area it drains becomes congested.",
    experience:
      "A blurred or missing area in part of the field, often noticed on waking, affecting one eye.",
    clinical:
      "Flame haemorrhages in the distribution of the affected vein, respecting the horizontal midline.",
    imaging: "OCT for oedema; angiography for non-perfusion.",
    profiles: ["vein_occlusion"],
    vocabulary: ["BRVO", "macular oedema", "anti-VEGF"],
    at: (s) => ({
      lesions: {
        flame: lerp(0.3, 1, s),
        dotBlot: 0.4 * s,
        cottonWool: 0.4 * s,
        venousEngorgement: 0.7,
        sector: { from: -Math.PI * 0.95, to: -Math.PI * 0.25 },
      },
    }),
    simulation: { kind: "curtain", retinalQuadrant: "superior" },
    gradable: true,
  },
  {
    id: "crvo",
    name: "Central retinal vein occlusion",
    region: "vitreoretina",
    view: "fundus",
    description: "The main vein draining the retina is blocked, congesting the whole retina.",
    experience: "Blurring across the vision of one eye, usually painless and often sudden.",
    clinical: "Haemorrhages in all four quadrants with dilated, tortuous veins.",
    imaging: "OCT, and angiography to assess perfusion.",
    profiles: ["vein_occlusion"],
    vocabulary: ["CRVO", "ischaemic", "non-ischaemic", "neovascular glaucoma"],
    at: (s) => ({
      lesions: {
        flame: lerp(0.4, 1, s),
        dotBlot: lerp(0.3, 0.9, s),
        cottonWool: 0.6 * s,
        venousEngorgement: 1,
      },
      delta: { vesselCalibre: 1.4, vesselTortuosity: 1.6 },
    }),
    simulation: { kind: "blur" },
    gradable: true,
  },
  {
    id: "crao",
    name: "Central retinal artery occlusion",
    region: "vitreoretina",
    view: "fundus",
    description: "The main artery supplying the retina is blocked, and the retina loses its blood supply.",
    experience: "Sudden, painless and profound loss of vision in one eye.",
    clinical: "A pale retina with a cherry-red spot at the fovea and attenuated arterioles.",
    vocabulary: ["CRAO", "cherry-red spot", "embolus"],
    at: (s) => ({
      lesions: { attenuation: lerp(0.4, 1, s), haze: 0.35 * s },
      delta: { pigmentation: 0.2, vesselCalibre: 0.55 },
    }),
    simulation: { kind: "peripheral_loss" },
    gradable: true,
  },
  {
    id: "retinitis_pigmentosa",
    name: "Retinitis pigmentosa",
    region: "vitreoretina",
    view: "fundus",
    description:
      "An inherited condition in which the light-sensing cells gradually stop working, usually from the periphery inwards.",
    experience:
      "Difficulty seeing in dim light, and a field that narrows over years. Central vision is often preserved until late.",
    clinical: "Bone-spicule pigmentation, attenuated arterioles and a waxy pale disc.",
    imaging: "Field testing, autofluorescence and electrophysiology.",
    profiles: ["inherited_retinal"],
    vocabulary: ["RP", "rod-cone dystrophy", "ERG", "night blindness"],
    at: (s) => ({
      lesions: { boneSpicules: lerp(0.3, 1, s), attenuation: 0.6 * s },
      delta: { vesselCalibre: 1 - 0.35 * s },
    }),
    simulation: { kind: "peripheral_loss" },
    gradable: true,
  },
  {
    id: "myopic_degeneration",
    name: "Myopic degeneration",
    region: "vitreoretina",
    view: "fundus",
    description:
      "In a long, highly short-sighted eye the retina and its underlying layers are stretched thin.",
    experience: "Reduced central sharpness, and sometimes distortion if the macula is involved.",
    clinical: "A tilted disc, peripapillary atrophy and a tessellated fundus.",
    vocabulary: ["high myopia", "posterior staphyloma", "lacquer cracks"],
    at: (s) => ({ lesions: { atrophy: 0.3 * s }, delta: { pigmentation: 0.25 } }),
    simulation: { kind: "blur" },
    gradable: true,
  },
  {
    id: "retinoschisis",
    name: "Retinoschisis",
    region: "vitreoretina",
    view: "fundus",
    description: "The retina splits within its own layers, rather than lifting away from the wall.",
    experience: "Usually nothing; it is generally found on examination.",
    clinical: "A smooth, immobile elevation, most often inferotemporal.",
    vocabulary: ["schisis", "inner leaf", "outer leaf"],
    at: (s) => ({ lesions: { detachment: 0.3 * s, sector: { from: 0.2, to: 1.1 } } }),
    gradable: false,
  },
  {
    id: "commotio",
    name: "Commotio retinae",
    region: "vitreoretina",
    view: "fundus",
    description: "Bruising of the retina after a blunt injury to the eye.",
    experience: "Blurring after an injury, which often settles over days to weeks.",
    clinical: "Retinal whitening in the area of impact.",
    vocabulary: ["commotio", "Berlin's oedema"],
    at: (s) => ({ lesions: { cottonWool: 0.8 * s, haze: 0.2 * s } }),
    simulation: { kind: "blur" },
    gradable: true,
  },
  {
    id: "vitreous_haemorrhage",
    name: "Vitreous haemorrhage",
    region: "vitreoretina",
    view: "fundus",
    description: "Blood in the vitreous cavity, which blocks light on its way to the retina.",
    experience:
      "A sudden shower of floaters, a red or dark haze, or loss of vision if the bleed is dense.",
    clinical: "Reduced or absent view of the fundus; ultrasound if the retina cannot be seen.",
    vocabulary: ["vitreous haemorrhage", "B-scan"],
    at: (s) => ({ lesions: { haze: lerp(0.3, 0.95, s) } }),
    simulation: { kind: "blur" },
    gradable: true,
  },
  {
    id: "after_laser_retinopexy",
    name: "After laser retinopexy",
    region: "vitreoretina",
    view: "fundus",
    description: "Laser applied around a break creates a scar that seals the retina down.",
    experience: "Usually nothing at the treated spot; new floaters or flashes are worth reporting.",
    clinical: "A confluent ring of chorioretinal scarring around the break.",
    profiles: ["retinal_detachment"],
    vocabulary: ["retinopexy", "barrier laser", "cryotherapy"],
    at: (s) => ({ lesions: { laserScars: lerp(0.4, 1, s), tear: 0.4 } }),
    annotations: [{ x: 0.76, y: 0.26, text: "The sealed break, ringed by laser scars" }],
    gradable: true,
  },
];
